In [147]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix

# Load and clean data
data_set = pd.read_csv('diabetes.csv')
zero_not_accepted = ['Glucose', 'BloodPressure', 'SkinThickness', 'BMI', 'Insulin']

for column in zero_not_accepted:
    data_set[column] = data_set[column].replace(0, np.NaN)
    mean = int(data_set[column].mean(skipna=True))
    data_set[column] = data_set[column].replace(np.NaN, mean)

# Prepare features and target
X = data_set.drop(columns='Outcome')
y = data_set['Outcome']

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# Scale features for KNN only
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# 1) Train and predict with KNN
knn = KNeighborsClassifier(n_neighbors=11, p=2, metric='euclidean')
knn.fit(X_train_scaled, y_train)
knn_pred = knn.predict(X_test_scaled)

# 2) Train and predict with Decision Tree (no scaling needed)
dt = DecisionTreeClassifier(random_state=0)
dt.fit(X_train, y_train)
dt_pred = dt.predict(X_test)

# Evaluate KNN
print("KNN Results:")
print("Accuracy:", accuracy_score(y_test, knn_pred))
print("F1 Score:", f1_score(y_test, knn_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, knn_pred))
print("\n" + "="*40 + "\n")

# Evaluate Decision Tree
print("Decision Tree Results:")
print("Accuracy:", accuracy_score(y_test, dt_pred))
print("F1 Score:", f1_score(y_test, dt_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, dt_pred))

KNN Results:
Accuracy: 0.8181818181818182
F1 Score: 0.6956521739130435
Confusion Matrix:
 [[94 13]
 [15 32]]


Decision Tree Results:
Accuracy: 0.6948051948051948
F1 Score: 0.5252525252525253
Confusion Matrix:
 [[81 26]
 [21 26]]


In [144]:
data_set = pd.read_csv('diabetes.csv')
zero_not_accepted=['Glucose','BloodPressure','SkinThickness','BMI','Insulin']
#clean data from zeros
for column in zero_not_accepted:
    data_set[column]=data_set[column].replace(0,np.NaN)
    mean=int(data_set[column].mean(skipna=True))
    data_set[column]=data_set[column].replace(np.NaN,mean)
    
X=data_set.drop(columns='Outcome')
y=data_set['Outcome']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)
#feature scaling
sc_X=StandardScaler()
X_train=sc_X.fit_transform(X_train)
X_test=sc_X.transform(X_test)

#define the model
model = KNeighborsClassifier(n_neighbors=13,p=2,metric='euclidean')
model.fit(X_train,y_train)
prediction=model.predict(X_test)
accuracy=accuracy_score(y_test,prediction)
print("Accuracy:", accuracy)
print("F1 Score:", f1_score(y_test, prediction))
print("Confusion Matrix:\n", confusion_matrix(y_test, prediction))
joblib.dump(model,'KNN.joblib')



Accuracy: 0.6948051948051948
F1 Score: 0.4946236559139785
Confusion Matrix:
 [[84 17]
 [30 23]]


['KNN.joblib']