In [21]:
import pandas as pd 
import numpy as np
from sklearn.model_selection import train_test_split , GridSearchCV
from sklearn.metrics import accuracy_score , f1_score, confusion_matrix, classification_report
from sklearn.datasets import make_classification
from sklearn.ensemble import AdaBoostClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC


In [37]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import AdaBoostClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, classification_report

# Data
X, y = make_classification(n_samples=2000, n_features=10, n_informative=8, n_redundant=2, random_state=11)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=11)

# AdaBoost with Decision Tree (default)
model1 = AdaBoostClassifier()
model1.fit(X_train, y_train)
pred1 = model1.predict(X_test)

print("\nDecision Tree:")
print("Accuracy:", accuracy_score(y_test, pred1))
print("F1 Score:", f1_score(y_test, pred1))
print(confusion_matrix(y_test, pred1))
print(classification_report(y_test, pred1))

# AdaBoost with Logistic Regression
model2 = AdaBoostClassifier(estimator=LogisticRegression())
model2.fit(X_train, y_train)
pred2 = model2.predict(X_test)

print("\nLogistic Regression:")
print("Accuracy:", accuracy_score(y_test, pred2))
print("F1 Score:", f1_score(y_test, pred2))
print(confusion_matrix(y_test, pred2))
print(classification_report(y_test, pred2))

# AdaBoost with SVM (use SAMME to avoid probability=True)
svc = SVC(kernel='linear')
model3_base = AdaBoostClassifier(estimator=svc, algorithm='SAMME')

# Hyperparameter grid
param_grid = {
    'n_estimators': [10, 25],
    'learning_rate': [0.01, 0.1, 1.0]
}

model_grid = GridSearchCV(model3_base, param_grid, cv=3, n_jobs=-1)
model_grid.fit(X_train, y_train)

# Best model
best_model = model_grid.best_estimator_
pred3 = best_model.predict(X_test)

print("\nSVM with AdaBoost (GridSearch):")
print("Best Params:", model_grid.best_params_)
print("Accuracy:", accuracy_score(y_test, pred3))
print("F1 Score:", f1_score(y_test, pred3))
print(confusion_matrix(y_test, pred3))
print(classification_report(y_test, pred3))



C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(



Decision Tree:
Accuracy: 0.815
F1 Score: 0.8072916666666666
[[171  34]
 [ 40 155]]
              precision    recall  f1-score   support

           0       0.81      0.83      0.82       205
           1       0.82      0.79      0.81       195

    accuracy                           0.81       400
   macro avg       0.82      0.81      0.81       400
weighted avg       0.82      0.81      0.81       400


Logistic Regression:
Accuracy: 0.785
F1 Score: 0.7736842105263158
[[167  38]
 [ 48 147]]
              precision    recall  f1-score   support

           0       0.78      0.81      0.80       205
           1       0.79      0.75      0.77       195

    accuracy                           0.79       400
   macro avg       0.79      0.78      0.78       400
weighted avg       0.79      0.79      0.78       400


SVM with AdaBoost (GridSearch):
Best Params: {'learning_rate': 0.1, 'n_estimators': 25}
Accuracy: 0.79
F1 Score: 0.7777777777777778
[[169  36]
 [ 48 147]]
              pr